version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - CRED_FILENAME=${CRED_FILENAME}
      - FILE_URL=${FILE_URL}
    volumes:
      - .:/usr/src/app
      - ./txts:/usr/src/app/txts
    restart: unless-stopped